# Generated by Django 5.0.7 on 2024-08-04 00:02

import django.db.models.deletion
import hello.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название категории')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание задачи')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('BLOCKED', 'Blocked'), ('DONE', 'Done')], default='NEW', max_length=25, verbose_name='статус задачи')),
                ('deadline', models.DateTimeField(default=hello.models.default_deadline, verbose_name='дата и время дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('title', models.CharField(max_length=100, unique_for_date='created_at', verbose_name='название задачи')),
                ('categories', models.ManyToManyField(blank=True, related_name='tasks', related_query_name='task', to='hello.category', verbose_name='категории задачи')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название задачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание задачи')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('BLOCKED', 'Blocked'), ('DONE', 'Done')], default='NEW', max_length=25, verbose_name='статус задачи')),
                ('deadline', models.DateTimeField(default=hello.models.default_deadline, verbose_name='дата и время дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', related_query_name='sub_task', to='hello.task', verbose_name='основная задача')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
