# Generated by Django 5.0.7 on 2024-08-05 00:42

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['-created_at'], 'verbose_name': 'SubTask'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task'},
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, verbose_name='название задачи'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='hello_category_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='subtask',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='hello_subtask_title_unique'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='hello_task_title_unique'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='"task_manager_category"',
        ),
        migrations.AlterModelTable(
            name='subtask',
            table='"task_manager_subtask"',
        ),
        migrations.AlterModelTable(
            name='task',
            table='"task_manager_task"',
        ),
    ]
